### ISSUE TITLE
No response after clicking on the "store package" button

### ISSUE THREAD

**Issue by hugues-koolsol** [pwa-builder/pwabuilder-blog#23]
Hello
I have tried to use the "Store package" button and there was no response after 60 seconds.

I have filled the 3 fields with the right information ( Package/Identité/Nom , Package/Identité/Éditeur , Package/Propriétés/NomAffichageÉditeur ) that I founded on the dashboard https://partner.microsoft.com/fr-fr/dashboard/...

Thank you for your help.

![image](https://user-images.githubusercontent.com/26767344/123953601-b25ae800-d9a7-11eb-82cf-40a2a9436910.png)

**Comment by JudahGabriel** [comment]
Hi @hugues-koolsol 

You opened an issue on our blog repository. Please open the issue on [our main repository](https://github.com/pwa-builder/pwabuilder/issues), and it'll get attention and fixes.
