### ISSUE TITLE
Enhance Layout for better readability

### ISSUE THREAD

**Issue by xstable** [pwa-builder/pwabuilder-blog#24]
Currently the blog is hard to read. 
You can't read links very well: 

![image](https://user-images.githubusercontent.com/1778068/124715153-f3508080-df02-11eb-8a98-213fe1c6b9bc.png)

Better make them #cfcfcf or something like that. 
I would prefer to not only have a deep-dark layout. If "dark-theme" better use a bg-color wich is a little bit lighter... and also provide an light-theme

**Comment by JudahGabriel** [comment]
Ah, we probably haven't tested in dark mode enough. I've lightened the links while in dark mode.
