### ISSUE TITLE
App notifications

### ISSUE THREAD

**Issue by whiwo** [pwa-builder/pwabuilder-blog#27]
In a previous thread, I asked why the app didn't 'push' notifications when there was a new post to the website. I was referred to another GitHub project for "[push notifications](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/serviceworker)," which are those annoying pop-ups every site has now to receive notifications that I never click on and wouldn't annoy my users with. 

What I'm interested in is the actual app itself that's installed on my website. There are no permissions set (which is great) except for notifications. Meaning, if something new is posted to the website, shouldn't it be able to notify people who've installed the app that there's a new post? Or, does this fall into the same catgegory as push notifications that require node.js and a bunch of other scripts that are not included in the actual app? 

I'm a novice but with the right instruction I can implement it. It would definitely give the app better usability as opposed to just being a shortcut on a user's device.

**Comment by JudahGabriel** [comment]
@whiwo 

You're commenting on the PWABuilder Blog repository, but I assume you're asking about push notifications for your PWA, partyfavorz, yeah?

The bad news, doing push notifications on the web takes a bit of effort if you're writing all the code yourself.

The good news is, there are push notifications services out there (including ones for WordPress sites, like [OneSignal Web Push Notifications](https://wordpress.org/plugins/onesignal-free-web-push-notifications/)) if you don't want to write the code to do it on your own. 

If you really, really want to roll your own push notifications, you'll need a database where you can store push notifications, server-side code to query the database and send push notifications, some JS code in your web app to subscribe a user, and finally, some additional code in your service worker to listen for the push event. If you want to pursue that, I recommend starting here: https://web.dev/push-notifications-overview/

We at PWABuilder have considered building a push notification service to make this whole process easier...it's just that we have a lot on our plate right now and there are existing services out there that do the same thing, so it's been low priority for us. 😊

**Comment by whiwo** [comment]
Thank you for the clarification and the suggestions. I'll look into the plugin.
