### ISSUE TITLE
PWA drastically slowing down mobile 

### ISSUE THREAD

**Issue by whiwo** [pwa-builder/pwabuilder-blog#29]
Since yesterday, my mobile site went from an A to C in Lighthouse. GT Metrix is worse (and they're usually more generous with their scoring system). 

I noticed that on mobile, the featured images wouldn't or couldn't load. Since nothing has really changed I did notice that the PWA wording changed where it just says "install" blah blah.com but that was only showing up on single posts as it wasn't loading on the front page (I had set the scope to https://partyfavorz.com/ not /).

Once I removed the manifest code and and the service worker JavaScript and cleared my cache, my scores jumped to 94 (where they were originally at) and the featured images on mobile were now loading as they had been. 

Clearly, some sort of push or change you made on the backend is causing loading issues for mobile devices (or at least mine). I had to remove it. Maybe check into it to see what the problem is because right now, it's unusable.

**Comment by JudahGabriel** [comment]
You're on the wrong repository. This is the blog repository. You're looking for the [PWABuilder repository](https://github.com/pwa-builder/pwabuilder/issues). Please open an issue there.
