### ISSUE TITLE
How to remove navigation tab and URL from android apps?

### ISSUE THREAD

**Issue by jonasnaves** [pwa-builder/pwabuilder-blog#31]
How to remove navigation tab and URL from android apps?
![image](https://user-images.githubusercontent.com/88113206/127391313-a528919b-8777-429d-a329-0c0c37b4ba58.png)

**Comment by JudahGabriel** [comment]
Wrong repository. Please open an issue [here](https://github.com/pwa-builder/pwabuilder/issues).
