### ISSUE TITLE
Community demos!

### ISSUE THREAD

**Issue by jgw96** [pwa-builder/pwabuilder-blog#56]
Opening this issue to discuss community submitted PWA demos.

**Comment by patrickmonteiro** [comment]
Hello @jgw96 , my twitter is: https://twitter.com/monteiropatrick

I have a post on TWA here: https://twitter.com/monteiropatrick/status/1401639208335417349

The playlist on youtube: https://youtube.com/playlist?list=PLBjvYfV_TvwJDPHU7VEANIa5vQz45xOJK

The article: https://how.kovi.work/publicando-um-pwa-na-google-play-store-31286907ec28

Apps on google play:

[AbaetéFest](https://play.google.com/store/apps/details?id=br.com.abaetefest.app.twa) - An application to publicize events, parties, sporting tournaments etc.

[E-estoque](https://play.google.com/store/apps/details?id=br.com.e_estoque.twa) - A stock app that works completely offline with indexedDB

[Quasar-notes](https://play.google.com/store/apps/details?id=app.netlify.quasar_notes_app.twa) - A simple app for notes and reminders, also with indexedDB

Do you need anything else?
