### ISSUE TITLE
512x512 or larger icon can be loaded succesfully from the network

### ISSUE THREAD

**Issue by marcosscorpain7** [pwa-builder/pwabuilder-blog#58]
Why do I get a score of 0 when I have already uploaded the 512*512 file.

**Comment by JudahGabriel** [comment]
Hi @marcosscorpain7 

You've opened an issue on the wrong repo. This is our blog repository. Please open an issue on https://github.com/pwa-builder/pwabuilder/issues, and include the URL you're trying to analyze with PWABuilder.
